server:
  port: 8082
logging:
  level:
    org.springframework.security: DEBUG
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/nvaultdb
        username : root
        password : nisum@06
        testWhileIdle : true
        validationQuery : SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect : org.hibernate.dialect.MySQL5Dialect 