server:
  port: 8083
logging:
  level:
    org.springframework.security: DEBUG

spring:
    mail:
      host: smtp.gmail.com
      username: ppadala@nisum.com
      password: xxxxxxxx
      properties:
                    mail:
                      smtp:
                        auth: true
                        socketFactory:
                                  port: 465
                                  class: javax.net.ssl.SSLSocketFactory
                                  fallback: false
    datasource:
        url: jdbc:mysql://localhost:3306/nvaultdb
        username : root
        password : root
        testWhileIdle : true
        validationQuery : SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect : org.hibernate.dialect.MySQL5Dialect                                   