server:
  port: 8083
logging:
  level:
    org.springframework.security: DEBUG

spring:
    mail:
      host: smtp.gmail.com
      username: ppadala@nisum.com
      password: 29nov2016
      properties:
                    mail:
                      smtp:
                        auth: true
                        socketFactory:
                                  port: 465
                                  class: javax.net.ssl.SSLSocketFactory
                                  fallback: false