server: 
     port : 9000
     address: 127.0.0.1
security: 
     sessions : NEVER
logging:
   level:
      org.springframework.security: DEBUG	
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/nvaultdb
        username : root
        password : root
        testWhileIdle : true
        validationQuery : SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect : org.hibernate.dialect.MySQL5Dialect 
    mail:
      mail:
      host: smtp.gmail.com
      username: nsuggula@nisum.com
      password: xxxxxx
      properties:
                    mail:
                      smtp:
                        auth: true
                        socketFactory:
                                  port: 465
                                  class: javax.net.ssl.SSLSocketFactory
                                  fallback: false
    http:
          multipart:
                    enabled: true
                    max-file-size: 10Mb
            
nv-path: /javed_backup/uploads
accessKey : AKIAJN6O4XIP2IDVE2EQ
securityKey : s/pg8vxxbENbAG9G18T+h8+UMCgLx+vt8lnCzhaU
homePath : home/
trashPath : trash/
archivePath : archive/  
   
   